=== adiwg/mdProfiles/json/profile-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "profile-schema",
  "version": "0.2.0",
  "type": "object",
  "description": "JSON schema for mdEditor profile definitions",
  "additionalProperties": false,
  "properties": {
    "identifier": {
      "type": "string"
    },
    "alternateId": {
      "type": "array",
      "description": "List of alternate identifiers for the profile definition",
      "items": {
        "type": "string"
      }
    },
    "namespace": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "components": {
      "$ref": "#/definitions/Components"
    },
    "nav": {
      "$ref": "#/definitions/Nav"
    }
  },
  "required": ["description", "identifier", "namespace", "title", "version"],
  "title": "Profile definition",
  "anyOf": [
    {
      "type": "object",
      "title": "components is required",
      "required": ["components"]
    },
    {
      "type": "object",
      "title": "nav is required",
      "required": ["nav"]
    }
  ],
  "definitions": {
    "Components": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "record": {
          "$ref": "#/definitions/Component"
        },
        "contact": {
          "$ref": "#/definitions/Component"
        },
        "dictionary": {
          "$ref": "#/definitions/Component"
        }
      },
      "title": "Components"
    },
    "Component": {
      "type": "object"
    },
    "Nav": {
      "type": "object",
      "additionalProperties": true,
      "propertyNames": {
        "enum": ["record", "contact", "dictionary"]
      },
      "patternProperties": {
        "{record|contact|dictionary": {
          "$ref": "#/definitions/NavItem"
        }
      },
      "title": "Nav"
    },
    "NavItem": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "target": {
            "type": "string"
          },
          "tip": {
            "type": "string"
          }
        },
        "required": ["target", "tip", "title"],
        "title": "NavItem"
      },
      "title": "Navigation Section"
    }
  }
}

=== adiwg/mdProfiles/resources/profiles/product.json
{
  "identifier": "product",
  "namespace": "org.adiwg.profile",
  "alternateId": ["lccProduct"],
  "title": "Product",
  "description": "Document a product, typically a data product generated by a project",
  "version": "1.0.0",
  "components": {
    "record": {
      "main": {
        "basicInformation": {
          "recordId": false
        },
        "citation": {
          "basicInformation": {
            "edition": false,
            "presentationForm": false
          },
          "onlineResource": {
            "protocol": false,
            "applicationProfile": false,
            "protocolRequest": false
          },
          "identifier": {
            "version": false,
            "description": false,
            "authority": {
              "basicInformation": {
                "alternateTitle": false
              },
              "onlineResource": {
                "protocol": false,
                "applicationProfile": false,
                "protocolRequest": false
              },
              "identifier": false
            }
          },
          "otherCitationDetails": false,
          "graphic": false
        },
        "environmentDescription": false,
        "timePeriod": {
          "identifier": false,
          "description": false,
          "periodName": false,
          "interval": false,
          "duration": false
        },
        "maintenance": {
          "scope": false
        },
        "graphicOverview": {
          "fileType": false,
          "onlineResource": {
            "protocol": false,
            "applicationProfile": false,
            "protocolRequest": false
          }
        }
      },
      "metadata": {
        "metadataIdentifier": {
          "version": false,
          "description": false,
          "authority": false
        },
        "parentMetadata": {
          "basicInformation": {
            "alternateTitle": false,
            "edition": false,
            "presentationForm": false
          },
          "identifier": false,
          "identifierSimple": {
            "version": false,
            "description": false,
            "authority": false
          },
          "series": false,
          "otherCitationDetails": false,
          "graphic": false
        },
        "onlineResource": {
          "protocol": false,
          "applicationProfile": false,
          "protocolRequest": false
        },
        "maintenance": false,
        "defaultLocale": false,
        "alternateMetadataReference": false
      },
      "extent": {
        "geographic": {
          "description": false,
          "containsData": false
        },
        "vertical": false,
        "temporal": false
      },
      "spatial": {
        "spatialReferenceSystem": {
          "referenceSystemIdentifier": {
            "version": false,
            "description": false,
            "authority": {
              "basicInformation": {
                "alternateTitle": false
              },
              "onlineResource": {
                "protocol": false,
                "applicationProfile": false,
                "protocolRequest": false
              },
              "identifier": false
            }
          }
        }
      },
      "taxonomy": {
        "collection": {
          "taxonomicSystem": {
            "citation": {
              "onlineResource": {
                "protocol": false,
                "applicationProfile": false,
                "protocolRequest": false
              },
              "identifier": false,
              "identifierSimple": {
                "authority": {
                  "basicInformation": {
                    "alternateTitle": false,
                    "dates": false
                  },
                  "onlineResource": {
                    "protocol": false,
                    "applicationProfile": false,
                    "protocolRequest": false
                  },
                  "identifier": false
                }
              },
              "identifierShort": false,
              "series": false,
              "otherCitationDetails": false,
              "graphic": false
            }
          }
        }
      },
      "distribution": {
        "distributor": {
          "transferOption": {
            "distributionUnit": false,
            "offlineOption": {
              "storage": {
                "density": false,
                "units": false
              }
            }
          }
        }
      },
      "constraints": {
        "graphic": false
      },
      "associated": {
        "resourceCitation": {
          "basicInformation": {
            "alternateTitle": false,
            "edition": false,
            "presentationForm": false
          },
          "identifier": false,
          "identifierSimple": false,
          "onlineResource": {
            "protocol": false,
            "applicationProfile": false,
            "protocolRequest": false
          },
          "identifierShort": {},
          "series": false,
          "otherCitationDetails": false,
          "graphic": false
        },
        "metadataCitation": {
          "basicInformation": {
            "alternateTitle": false,
            "edition": false,
            "presentationForm": false
          },
          "identifier": false,
          "identifierSimple": false,
          "onlineResource": {
            "protocol": false,
            "applicationProfile": false,
            "protocolRequest": false
          },
          "identifierShort": {},
          "series": false,
          "otherCitationDetails": false,
          "graphic": false
        }
      },
      "documents": {
        "citation": {
          "identifier": false,
          "identifierSimple": false,
          "onlineResource": {
            "protocol": false,
            "applicationProfile": false,
            "protocolRequest": false
          },
          "identifierShort": {},
          "otherCitationDetails": false,
          "graphic": false
        }
      }
    },
    "contact": {},
    "dictionary": {}
  },
  "nav": {
    "record": [
      {
        "title": "Main",
        "target": "record.show.edit.main",
        "tip": "Basic information about the product."
      },
      {
        "title": "Metadata",
        "target": "record.show.edit.metadata",
        "tip": "Information about the metadata for the product."
      },
      {
        "title": "Keywords",
        "target": "record.show.edit.keywords",
        "tip": "Terms used to describe the product."
      },
      {
        "title": "Extent",
        "target": "record.show.edit.extent",
        "tip": "Information describing the bounds of the product."
      },
      {
        "title": "Spatial",
        "target": "record.show.edit.spatial",
        "tip": "Information concerning the spatial attributes of the product."
      },
      {
        "title": "Lineage",
        "target": "record.show.edit.lineage",
        "tip": "Information on the history of the product."
      },
      {
        "title": "Taxonomy",
        "target": "record.show.edit.taxonomy",
        "tip": "Information on the taxa associated with the product."
      },
      {
        "title": "Distribution",
        "target": "record.show.edit.distribution",
        "tip": "Information about obtaining the product."
      },
      {
        "title": "Constraints",
        "target": "record.show.edit.constraint",
        "tip": "Information about constraints applied to the product."
      },
      {
        "title": "Associated",
        "target": "record.show.edit.associated",
        "tip": "Other resources with a defined relationship to the product."
      },
      {
        "title": "Documents",
        "target": "record.show.edit.documents",
        "tip": "Other documents related to, but not defining, the product."
      },
      {
        "title": "Dictionaries",
        "target": "record.show.edit.dictionary",
        "tip": "Data dictionaries associated with the product."
      }
    ],
    "dictionary": [
      {
        "title": "Main",
        "target": "dictionary.show.edit.index",
        "tip": "Basic information about the dictionary."
      },
      {
        "title": "Citation",
        "target": "dictionary.show.edit.citation",
        "tip": "The citation for the dictionary."
      },
      {
        "title": "Domains",
        "target": "dictionary.show.edit.domain",
        "tip": "Information about defined value lists."
      },
      {
        "title": "Entities",
        "target": "dictionary.show.edit.entity",
        "tip": "Information about entities(tables) and attributes(columns or fields)."
      }
    ]
  }
}

=== adiwg/mdProfiles/resources/profiles/full.json
{
  "identifier": "full",
  "namespace": "org.adiwg.profile",
  "alternateId": ["full"],
  "title": "Full",
  "description": "Every supported component",
  "version": "VERSION",
  "components": {
    "record": {},
    "contact": {},
    "dictionary": {}
  },
  "nav": {
    "record": [
      {
        "title": "Main",
        "target": "record.show.edit.main",
        "tip": "Basic information about the resource."
      },
      {
        "title": "Metadata",
        "target": "record.show.edit.metadata",
        "tip": "Information about the metadata for the resource."
      },
      {
        "title": "Keywords",
        "target": "record.show.edit.keywords",
        "tip": "Terms used to describe the resource."
      },
      {
        "title": "Extent",
        "target": "record.show.edit.extent",
        "tip": "Information describing the bounds of the resource."
      },
      {
        "title": "Spatial",
        "target": "record.show.edit.spatial",
        "tip": "Information concerning the spatial attributes of the resource."
      },
      {
        "title": "Lineage",
        "target": "record.show.edit.lineage",
        "tip": "Information on the history of the resource."
      },
      {
        "title": "Data Quality",
        "target": "record.show.edit.dataquality",
        "tip": "Information about quality of the underlying resource data"
      },
      {
        "title": "Taxonomy",
        "target": "record.show.edit.taxonomy",
        "tip": "Information on the taxa associated with the resource."
      },
      {
        "title": "Distribution",
        "target": "record.show.edit.distribution",
        "tip": "Information about obtaining the resource."
      },
      {
        "title": "Constraints",
        "target": "record.show.edit.constraint",
        "tip": "Information about constraints applied to the resource."
      },
      {
        "title": "Associated",
        "target": "record.show.edit.associated",
        "tip": "Other resources with a defined relationship to the resource."
      },
      {
        "title": "Documents",
        "target": "record.show.edit.documents",
        "tip": "Other documents related to, but not defining, the resource."
      },
      {
        "title": "Funding",
        "target": "record.show.edit.funding",
        "tip": "Information about funding allocated to development of the resource."
      },
      {
        "title": "Dictionaries",
        "target": "record.show.edit.dictionary",
        "tip": "Data dictionaries associated with the resource."
      }
    ],
    "dictionary": [
      {
        "title": "Main",
        "target": "dictionary.show.edit.index",
        "tip": "Basic information about the dictionary."
      },
      {
        "title": "Citation",
        "target": "dictionary.show.edit.citation",
        "tip": "The citation for the dictionary."
      },
      {
        "title": "Domains",
        "target": "dictionary.show.edit.domain",
        "tip": "Information about defined value lists."
      },
      {
        "title": "Entities",
        "target": "dictionary.show.edit.entity",
        "tip": "Information about entities(tables) and attributes(columns or fields)."
      }
    ]
  }
}
